import { SingletonDemo } from './creational/singleton';
import { AbstractFactoryDemo } from './creational/abstract_factory';
import { FactoryDemo } from './creational/factory';
import { BuilderDemo } from './creational/builder';
import { PrototypeDemo } from './creational/prototype';
import { AdapterDemo } from './structural/adapter';
import { BridgeDemo } from './structural/bridge';
import { CompositeDemo } from './structural/composite';
import { DecoratorDemo } from './structural/decorator';
import { FacedeDemo } from './structural/facade';
import { FlyWeightDemo } from './structural/flyweight';
import { ProxyDemo } from './structural/proxy';
import { ChainResponsibilityDemo } from './behavioral/chain_of_responsibility';
import { CommandDemo } from './behavioral/command';
import { IteratorDemo } from './behavioral/iterator';
import { MediatorDemo } from './behavioral/mediator';
import { InterpreterDemo } from './behavioral/interpreter';
import { MementoDemo } from './behavioral/memento';
import { ObserverDemo } from './behavioral/observer';
import { StrategyDemo } from './behavioral/strategy';
import { StateDemo } from './behavioral/state';
import { TemplateDemo } from './behavioral/template';
//Algorithm
import { CalculatorDemo } from './algorithm/calculator';

SingletonDemo.execute(false);
AbstractFactoryDemo.execute(false);
FactoryDemo.execute(false);
BuilderDemo.execute(false);
PrototypeDemo.execute(false);
AdapterDemo.execute(false);
BridgeDemo.execute(false);
CompositeDemo.execute(false);
DecoratorDemo.execute(false);
CalculatorDemo.execute(false);
FacedeDemo.execute(false);
FlyWeightDemo.execute(false);
ProxyDemo.execute(false);
ChainResponsibilityDemo.execute(false);
CommandDemo.execute(false);
IteratorDemo.execute(false);
MediatorDemo.execute(false);
InterpreterDemo.execute(false);
MementoDemo.execute(false);
ObserverDemo.execute(false);
StrategyDemo.execute(false);
StateDemo.execute(false);
TemplateDemo.execute(true);